### ISSUE TITLE
Add ton connect sdk

### ISSUE THREAD

**Issue by mishailovic** [tangem/tangem-app-ios-old#3078]
While the Tangem app already has wallet connect for etherium, which allows you to manage all of your crypto assets inside eth network, it would be nice to see ton connect feature. Toncoin is already on 11th place on CMC, yet you can’t perform basic actions such as Jetton transfers inside Tangem app.

**Comment by tureck1y** [comment]
Thank you for reaching out and for your suggestion! We would love to add support for TonConnect, but its implementation is a bit more complex compared to WalletConnect, mainly due to the lack of an SDK and the need to set up custom backend. However, we're keeping a close eye on developments, and it’s something we may consider in the future.
