### ISSUE TITLE
Base Tokens Not Showing Price

### ISSUE THREAD

**Issue by QuixThe2nd** [tangem/tangem-app-ios-old#3277]
Tokens on the Base chain aren't correctly showing prices, like on other chains, despite being listed on CoinGecko. Prices do show for other tokens manually added via contract address, as long as they're listed on CoinGecko, so I believe this is a bug with the Base layer specifically. For me personally, I have this issue with $DEGEN.

CoinGecko Listing: https://www.coingecko.com/en/coins/degen-base

Price not showing:
![image](https://github.com/tangem/tangem-app-ios/assets/25378634/f9d19f96-b90d-404a-ad08-0cb69c692c42)

This issue has also been reported by other users on the Telegram:
![image](https://github.com/tangem/tangem-app-ios/assets/25378634/cc18b154-664b-4e92-b624-89be1296f466)

**Comment by kingomarnajjar** [comment]
It's the exact same issue for me!

Please fix so we can see the prices, this is necessary for me to keep using it

**Comment by m3g0byt3** [comment]
Thanks for reporting, the issue has been fixed

$DEGEN and other popular tokens from this list https://www.coingecko.com/en/categories/base-ecosystem should already be available in the app, and their prices should be displayed as well.

Tokens previously added manually should update automatically after restarting the app. 
If this is not the case, please delete them from the app and re-add them using the 'Manage tokens' screen.

If the issue persists, please contact technical support via email

**Comment by QuixThe2nd** [comment]
Thank you for the quick fix @m3g0byt3. Will prices also be shown for tokens on the Base network that are listed on CoinGecko but need to be added manually on the Tangem app in the future?

**Comment by m3g0byt3** [comment]
@QuixThe2nd 
All tokens are imported from CMC/CoinGecko in a semi-automatic fashion, with some moderation (e.g. filtering due to low scores on antirug checkers, etc) being applied before a particular token becomes available on the 'Manage tokens' screen in the app. This is the case for all supported networks, not something Base-specific.

If a particular token (on a supported network) is already listed on CMC/CoinGecko but not yet available in the app, please contact support via email for details. There may be some issues (again, like low antirug checker score, for example) preventing it from being added to the list of tokens on the 'Manage tokens' screen.
